export const initialLevel:Level = {
    song: "song",
    artist: "artist",
    chart: "",
    thumbnail: "",
    difficulty: 1,
    bpm: "100",
    backgroundColor: 0x000000,
    notelines: [
      {
        bpm: 100,
        key: "KeyA",
        notes: [],
        events:[],
        filters:[],
        blendMode: "",
        mask: "",
        transform:{position:[-.3, 0], rotation:0, scale:[1, 1], alpha:1, pivot:[0, 0], tint:0xffffff},
      },
      {
        bpm: 100,
        key: "KeyA",
        notes: [],
        events:[],
        filters:[],
        blendMode: "",
        mask: "",
        transform:{position:[-.1, 0], rotation:0, scale:[1, 1], alpha:1, pivot:[0, 0], tint:0xffffff},
      },
      {
        bpm: 100,
        key: "KeyA",
        notes: [],
        events:[],
        filters:[],
        blendMode: "",
        mask: "",
        transform:{position:[.1, 0], rotation:0, scale:[1, 1], alpha:1, pivot:[0, 0], tint:0xffffff},
      },
      {
        bpm: 100,
        key: "KeyA",
        notes: [],
        events:[],
        filters:[],
        blendMode: "",
        mask: "",
        transform:{position:[.3, 0], rotation:0, scale:[1, 1], alpha:1, pivot:[0, 0], tint:0xffffff},
      },
    ],
    camera: {
      events:[],
      filters:[],
      blendMode: "",
      mask: "",
      transform:{position:[0, 0], rotation:0, scale:[1, 1], alpha:1, pivot:[0, 0], tint:0xffffff},
    },
    sprites: [],
    texts: [],
    blocks: [{
      offset: 0,
      split: 4,
      bpm: 100,
      length: 4,
    }]
  }